### ISSUE TITLE
Long URLs should not appear on printed handouts

### ISSUE THREAD

**Issue by maxg** [maxg/handx#11]
We could remove Bootstrap's URL printing entirely:

```css
@media print {
  a[href]:after {
    content: "";
  }
}
```

But perhaps we can cut off URLs after a maximum length instead?
